name: Build
on: [push]
jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@master

      - name: Get deps
        run: yarn

      - name: Add `node_modules/.bin` to path
        run: echo ::add-path::$(yarn bin)

      - name: "elm-format"
        uses: sparksp/elm-format-action@v1

      - name: "elm-review"
        uses: sparksp/elm-review-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build asset
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static