name: Build
on: [push]
jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Set Node.js
      #   uses: actions/setup-node@master

      # - name: Get deps
      #   run: npm install

      - name: elm-review
        uses: sparksp/elm-review-action@v1.0.4

      # - name: Build asset
      #   run: npm build
