name: Build
on: [push]
jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@master

      - name: Get deps
        run: yarn

      - name: "elm-format"
        uses: sparksp/elm-format-action@v1

      - name: "elm-review"
        uses: sparksp/elm-review-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build asset
        run: npm build
